Repository depromeet/16th-team6-Android, pull requests merged in 2025-03, with the labels that each got.

#18 [#16] 홈 UI 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/CharacterSpeechBubble.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/CurrentLocationSheet.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/LocationText.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/MapView.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/PrimaryButton.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/SpeechBubble.kt
  app/src/main/res/drawable/ic_all_acha_character.xml
  app/src/main/res/drawable/ic_home_current_location.xml
  app/src/main/res/drawable/ic_home_location_green.xml
  app/src/main/res/drawable/ic_home_location_grey.xml
  app/src/main/res/drawable/ic_home_start_marker.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feat

#22 [#21] FCM 알림 구현
  .github/workflows/android_ci.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/depromeet/team6/data/datalocal/service/FcmService.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/MainActivity.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: feat

#20 [#13] 잠금화면 알림 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/depromeet/team6/data/datalocal/builder/SimpleNotificationBuilder.kt
  app/src/main/java/com/depromeet/team6/data/datalocal/manager/BaseForegroundServiceManager.kt
  app/src/main/java/com/depromeet/team6/data/datalocal/manager/Extension.kt
  app/src/main/java/com/depromeet/team6/data/datalocal/permission/PermissionUtil.kt
  app/src/main/java/com/depromeet/team6/data/datalocal/service/LockReceiver.kt
  app/src/main/java/com/depromeet/team6/data/datalocal/service/LockService.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/lock/LockActivity.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/lock/LockContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/lock/LockScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/lock/LockScreenNavigator.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/lock/LockViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/MainActivity.kt
  app/src/main/res/values/strings.xml
Labels: feat

#35 [#34] lint 적용 및 빌드 오류 해결
  .github/workflows/android_ci.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/depromeet/team6/presentation/ui/course/CourseViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/MainActivity.kt
Labels: bug

#32 [#13] 카카오 로그인 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/depromeet/team6/Team6App.kt
  app/src/main/java/com/depromeet/team6/data/datalocal/datasource/UserInfoLocalDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/AuthRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/DummyRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/interceptor/AuthInterceptor.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/request/dummy/RequestDummyDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/request/signup/RequestSignUpDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/base/ApiResponse.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/dummy/DummyResponseDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/user/ResponseAuthDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/user/ResponseCheckDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/AuthService.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/DummyService.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/util/Constraints.kt
  app/src/main/java/com/depromeet/team6/data/mapper/DummyMapper.kt
  app/src/main/java/com/depromeet/team6/data/mapper/todata/SignUpMapper.kt
  app/src/main/java/com/depromeet/team6/data/mapper/todomain/ResponseAuthDtoMapper.kt
  app/src/main/java/com/depromeet/team6/data/mapper/todomain/ResponseCheckDtoMapper.kt
  app/src/main/java/com/depromeet/team6/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/com/depromeet/team6/data/repositoryimpl/UserInfoRepositoryImpl.kt
  app/src/main/java/com/depromeet/team6/di/NetworkModule.kt
  app/src/main/java/com/depromeet/team6/di/RepositoryModule.kt
  app/src/main/java/com/depromeet/team6/di/ServiceModule.kt
  app/src/main/java/com/depromeet/team6/di/qualifier/Qualifier.kt
  app/src/main/java/com/depromeet/team6/domain/model/Auth.kt
  app/src/main/java/com/depromeet/team6/domain/model/SignUp.kt
  app/src/main/java/com/depromeet/team6/domain/repository/AuthRepository.kt
  app/src/main/java/com/depromeet/team6/domain/repository/UserInfoRepository.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetCheckUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetLoginUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/PostSignUpUseCase.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/login/LoginContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/login/LoginScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/depromeet/team6/presentation/util/Constraints.kt
  app/src/main/java/com/depromeet/team6/presentation/util/modifier/ModifierExt.kt
  app/src/main/java/com/depromeet/team6/ui/theme/Color.kt
  app/src/main/res/drawable/ic_login_kakao.xml
  app/src/main/res/drawable/ic_login_logo.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: feat

#43 [#17] 온보딩 추가 로직 구현
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/AuthRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/AuthService.kt
  app/src/main/java/com/depromeet/team6/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/com/depromeet/team6/domain/repository/AuthRepository.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/PostLogoutUseCase.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/login/LoginScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/OnboardingScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/component/OnboardingSearchLocationItem.kt
  app/src/main/java/com/depromeet/team6/presentation/util/context/ContextExt.kt
  app/src/main/res/drawable/ic_all_adrress_devider.xml
Labels: feat

#49 [#45] 웹뷰 컴포넌트 구현
  app/build.gradle.kts
  app/src/main/java/com/depromeet/team6/presentation/ui/common/view/AtChaWebView.kt
  app/src/main/java/com/depromeet/team6/presentation/util/Constraints.kt
  gradle/libs.versions.toml
Labels: feat

#50 [#44] mock 데이터 추가 및 경로검색 navigator 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/itinerary/MockCourseResponse.kt
  app/src/main/java/com/depromeet/team6/data/repositoryimpl/MockSearchDataImpl.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/LoadMockSearchDataUseCase.kt
  app/src/main/java/com/depromeet/team6/presentation/model/course/LegInfo.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/alarm/NotificationReceiver.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/alarm/NotificationScheduler.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/alarm/NotificationTimeConstants.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/common/AnimatedSnackbar.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/common/AtchaCommonBottomSheet.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/common/StableImage.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/course/CourseViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/course/component/LastTransportInfoList.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/course/component/TransportTabMenu.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/CourseSearchContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/CourseSearchScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/CourseSearchViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/CourseAppBar.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/CourseInfoDetail.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/CourseInfoDetailItem.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/CourseInfoSimple.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/DestinationSearchBar.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/LastTransportInfoItem.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/LastTransportInfoList.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/TabRowMinTab0dp.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/TransportCourseInfo.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/TransportTabMenu.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/TransportTabRow.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/navigation/CourseSearchNavigation.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/ItineraryContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/ItineraryScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/ItineraryViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/LegInfoDummyProvider.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/component/ItineraryDetail.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/component/ItineraryMap.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/component/ItinerarySummary.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/component/SummaryBarChart.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/navigation/ItineraryNavigation.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/navigation/MainNavHost.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/navigation/MainNavigator.kt
  app/src/main/java/com/depromeet/team6/presentation/util/Dimens.kt
  app/src/main/java/com/depromeet/team6/presentation/util/view/SnackbarController.kt
  app/src/main/java/com/depromeet/team6/ui/theme/Color.kt
  app/src/main/res/raw/mock_data.json
  app/src/main/res/values/strings.xml
Labels: feat

#48 [#42] 홈 사용자, 지도 위치 연결
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/LocationsRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/locations/ResponseAddressDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/LocationsService.kt
  app/src/main/java/com/depromeet/team6/data/mapper/todomain/ResponseAddressDtoMapper.kt
  app/src/main/java/com/depromeet/team6/data/repositoryimpl/LocationsRepositoryImpl.kt
  app/src/main/java/com/depromeet/team6/domain/model/Address.kt
  app/src/main/java/com/depromeet/team6/domain/repository/LocationsRepository.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetAddressFromCoordinatesUseCase.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/MapView.kt
  app/src/main/java/com/depromeet/team6/presentation/util/Constraints.kt
Labels: feat

#56 [#23] 출발지 검색 화면 구현
  .DS_Store
  app/.DS_Store
  app/.gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/depromeet/team6/Team6App.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/interceptor/AuthInterceptor.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/itinerary/MockCourseResponse.kt
  app/src/main/java/com/depromeet/team6/domain/model/HomeSearchLocation.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/DummyUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/LoadMockSearchDataUseCase.kt
  app/src/main/java/com/depromeet/team6/presentation/model/course/LastTransportInfo.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/alarm/NotificationScheduler.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/alarm/NotificationTimeConstants.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/CourseSearchScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/CourseSearchViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/LastTransportInfoItem.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/LastTransportInfoList.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/TransportTabMenu.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/navigation/CourseSearchNavigation.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/AfterRegisterSheet.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/CharacterSpeechBubble.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/CourseTextButton.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/FinishCourseDetailButton.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/ItineraryContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/ItineraryScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/ItineraryViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/component/ItineraryMap.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/component/ItinerarySummary.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/navigation/MainNavHost.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/navigation/MainNavigator.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/SearchLocationContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/SearchLocationScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/SearchLocationViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/component/BackTopBar.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/component/SearchDepartureTextField.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/component/SearchHistoryEmptyContainer.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/component/SearchHistoryItem.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/component/SearchLocationItem.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/component/SearchLocationTextField.kt
  app/src/main/java/com/depromeet/team6/ui/theme/Theme.kt
  app/src/main/res/raw/mock_data.json
  app/src/main/res/values/strings.xml
Labels: feat

#60 [#31] 대중교통 관련 디자인 시스템 업데이트
  app/build.gradle.kts
  app/src/main/java/com/depromeet/team6/presentation/ui/common/AtchaCommonBottomSheet.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/common/TransportVectorIcon.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/CourseInfoDetailItem.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/MapView.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/LegInfoDummyProvider.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/component/ItineraryMap.kt
  app/src/main/java/com/depromeet/team6/presentation/util/Dimens.kt
  app/src/main/java/com/depromeet/team6/ui/theme/Color.kt
  app/src/main/res/drawable/ic_all_bus_red.xml
  app/src/main/res/drawable/ic_all_walk_grey.xml
  app/src/main/res/drawable/ic_home_start_marker.xml
  app/src/main/res/drawable/map_marker_arrival.xml
  app/src/main/res/drawable/map_marker_departure.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
Labels: feat

#66 [#61]2차 MVP에 맞는 온보딩 UI 구현
  app/src/main/java/com/depromeet/team6/data/dataremote/interceptor/AuthInterceptor.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/locations/ResponseAddressDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/user/ResponseReissueDto.kt
  app/src/main/java/com/depromeet/team6/data/mapper/todomain/ResponseAddressDtoMapper.kt
  app/src/main/java/com/depromeet/team6/domain/model/Address.kt
  app/src/main/java/com/depromeet/team6/presentation/mapper/LocationListMapper.kt
  app/src/main/java/com/depromeet/team6/presentation/mapper/LocationMapper.kt
  app/src/main/java/com/depromeet/team6/presentation/model/location/Location.kt
  app/src/main/java/com/depromeet/team6/presentation/type/OnboardingPermissionType.kt
  app/src/main/java/com/depromeet/team6/presentation/type/OnboardingType.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/common/bottomsheet/AtChaLcationSettingBottomSheet.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/MapView.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/MainViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/navigation/MainNavigator.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/OnboardingContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/OnboardingScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/component/OnboardingAlarmSelector.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/component/OnboardingMapView.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/component/OnboardingPermissionBottomSheet.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/component/OnboardingPermissionDeniedBottomSheet.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/component/OnboardingSearchLocationItem.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/component/OnboardingSearchPopup.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/component/OnboardingSearchTextField.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/component/OnboardingSelectedHome.kt
  app/src/main/java/com/depromeet/team6/presentation/util/modifier/ModifierExt.kt
  app/src/main/java/com/depromeet/team6/presentation/util/permission/PermissionUtil.kt
  app/src/main/java/com/depromeet/team6/presentation/util/toast/AtChaToastMessage.kt
  app/src/main/java/com/depromeet/team6/presentation/util/view/LocationListExt.kt
  app/src/main/res/drawable/bg_atcha_toast_background.xml
  app/src/main/res/drawable/ic_map_marker_setting.xml
  app/src/main/res/drawable/ic_onboarding_bottom_sheet_bell_16.xml
  app/src/main/res/drawable/ic_onboarding_bottom_sheet_gps_16.xml
  app/src/main/res/drawable/ic_onboarding_close.xml
  app/src/main/res/drawable/ic_onboarding_current_location.xml
  app/src/main/res/layout/atcha_toast.xml
  app/src/main/res/values/strings.xml
Labels: feat

#67 [#61]2차 MVP에 온보딩 UI 1차 디자인 QA 사항 반영
  app/src/main/java/com/depromeet/team6/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/OnboardingScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/component/OnboardingSelectLocationButton.kt
  app/src/main/java/com/depromeet/team6/presentation/util/toast/AtChaToastMessage.kt
  app/src/main/res/layout/atcha_toast.xml
  app/src/main/res/values/themes.xml
Labels: feat

#79 [#72] 경로상세 버스경로 1차 구현
  app/build.gradle.kts
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/AuthRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/CourseRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/TransitsRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/request/exeption/RequestException.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/transits/ResponseBusArrivalsDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/transits/ResponseBusPositionsDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/transits/ResponseCourseSearchDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/user/ResponseUserInfoDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/AuthService.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/CourseService.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/LocationsService.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/TransitsService.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/util/Constraints.kt
  app/src/main/java/com/depromeet/team6/data/mapper/todomain/ResponseBusArrivalDtoMapper.kt
  app/src/main/java/com/depromeet/team6/data/mapper/todomain/ResponseBusPositionsDtopMapper.kt
  app/src/main/java/com/depromeet/team6/data/mapper/todomain/ResponseCourseSearchDtoMapper.kt
  app/src/main/java/com/depromeet/team6/data/mapper/todomain/ResponseUserInfoDtoMapper.kt
  app/src/main/java/com/depromeet/team6/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/com/depromeet/team6/data/repositoryimpl/CourseSearchRepositoryImpl.kt
  app/src/main/java/com/depromeet/team6/data/repositoryimpl/TransitsRepositoryImpl.kt
  app/src/main/java/com/depromeet/team6/di/RepositoryModule.kt
  app/src/main/java/com/depromeet/team6/di/ServiceModule.kt
  app/src/main/java/com/depromeet/team6/domain/model/BusArrival.kt
  app/src/main/java/com/depromeet/team6/domain/model/BusPosition.kt
  app/src/main/java/com/depromeet/team6/domain/model/BusStatus.kt
  app/src/main/java/com/depromeet/team6/domain/model/UserInfo.kt
  app/src/main/java/com/depromeet/team6/domain/repository/AuthRepository.kt
  app/src/main/java/com/depromeet/team6/domain/repository/CourseSearchRepository.kt
  app/src/main/java/com/depromeet/team6/domain/repository/TransitsRepository.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetBusArrivalUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetBusPositionsUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetCourseSearchResultsUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetUserInfoUseCase.kt
  app/src/main/java/com/depromeet/team6/presentation/model/bus/BusArrivalParameter.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/BusCourseContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/BusCourseScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/BusCourseViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/component/BusStationItem.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/navigation/BusCourseNavigation.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/common/view/AtChaLoadingView.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/CourseInfoDetailItem.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/CourseInfoSimple.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/ItineraryScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/navigation/ItineraryNavigation.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/navigation/MainNavHost.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/navigation/MainNavigator.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/mypage/MypageContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/mypage/MypageScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/mypage/MypageViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/mypage/component/MyPageConfirmDialog.kt
  app/src/main/java/com/depromeet/team6/presentation/util/view/TransportTypeUiMapper.kt
  app/src/main/res/drawable/ic_all_bus_18.xml
  app/src/main/res/drawable/ic_bus_course_info_12.xml
  app/src/main/res/drawable/ic_bus_station_check_14.xml
  app/src/main/res/values/strings.xml
Labels: feat

#81 [#80] Tmap SDK Version 수정
  app/build.gradle.kts
  app/libs/tmap-sdk-1.9.aar
  app/libs/tmap-sdk-2.1.aar
Labels: fix

#84 [#82] 프로덕션 엑세스 수정안
  app/build.gradle.kts
  app/src/main/java/com/depromeet/team6/data/mapper/todomain/ResponseCourseSearchDtoMapper.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/ItineraryScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/component/ItineraryInfoDetail.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/component/ItineraryInfoDetailLegs.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/component/ItineraryMap.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/component/ItinerarySummary.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/navigation/ItineraryNavigation.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/navigation/MainNavHost.kt
  app/src/main/java/com/depromeet/team6/presentation/util/Dimens.kt
Labels: fix
