Repository depromeet/16th-team6-Android, pull requests merged in 2025-04, with the labels that each got.

#93 [#72] 경로상세 버스경로 구현
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/transits/ResponseBusPositionsDto.kt
  app/src/main/java/com/depromeet/team6/data/mapper/todomain/ResponseBusPositionsDtopMapper.kt
  app/src/main/java/com/depromeet/team6/domain/model/BusArrival.kt
  app/src/main/java/com/depromeet/team6/domain/model/BusPosition.kt
  app/src/main/java/com/depromeet/team6/domain/model/BusStatus.kt
  app/src/main/java/com/depromeet/team6/presentation/model/bus/BusPositionParameter.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/BusCourseContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/BusCourseScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/BusCourseViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/component/BusStationItem.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/component/BusStatusIcon.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/common/text/AtchaRemainTimeText.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/component/OnboardingSearchPopup.kt
  app/src/main/java/com/depromeet/team6/ui/theme/Color.kt
  app/src/main/res/drawable/ic_all_course_refresh.xml
  app/src/main/res/drawable/ic_bus_course_position.xml
  app/src/main/res/drawable/ic_bus_course_position_airport_20.xml
  app/src/main/res/drawable/ic_bus_course_position_main_line_20.xml
  app/src/main/res/drawable/ic_bus_course_position_regular_20.xml
  app/src/main/res/drawable/ic_bus_course_position_town_20.xml
  app/src/main/res/drawable/ic_bus_course_position_wide_area_20.xml
  app/src/main/res/drawable/ic_bus_turn_point.xml
Labels: feat

#85 [#57] 홈 출발지 텍스트 검색 구현
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/LocationsRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/request/search/RequestSearchHistoryDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/LocationsService.kt
  app/src/main/java/com/depromeet/team6/data/mapper/todata/SearchHistoryMapper.kt
  app/src/main/java/com/depromeet/team6/data/repositoryimpl/LocationsRepositoryImpl.kt
  app/src/main/java/com/depromeet/team6/domain/model/HomeSearchLocation.kt
  app/src/main/java/com/depromeet/team6/domain/model/SearchHistory.kt
  app/src/main/java/com/depromeet/team6/domain/repository/LocationsRepository.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/DeleteAllSearchHistoryUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/DeleteSearchHistoryUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetSearchHistoriesUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/PostSearchHistoriesUseCase.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/CurrentLocationSheet.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/navigation/MainNavHost.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/navigation/MainNavigator.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/SearchLocationContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/SearchLocationScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/SearchLocationViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/component/BackTopBar.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/component/SearchDepartureTextField.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/component/SearchHistoryContainer.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/component/SearchHistoryItem.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/component/SearchLocationItem.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/component/SearchLocationMapView.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/component/SearchLocationTextField.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/navigation/SearchLocationNavigation.kt
  app/src/main/java/com/depromeet/team6/ui/theme/Color.kt
  app/src/main/res/drawable/ic_home_location_grey_3dp.xml
  app/src/main/res/drawable/ic_search_circle_close.xml
  app/src/main/res/drawable/ic_search_list_close_grey.xml
  app/src/main/res/drawable/ic_search_list_map_28dp.xml
  app/src/main/res/values/strings.xml
Labels: feat

#97 [#90] 알림 등록 후 departurePoint 로드 문제 해결
  app/src/main/java/com/depromeet/team6/presentation/ui/common/TransportVectorIconWithText.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/AfterRegisterMap.kt
Labels: fix

#99 [#98] 홈 화면 출발지 없을 때 주소로 대체
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeViewModel.kt
Labels: fix

#92 [#86] 디자인 QA 반영
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/CurrentLocationSheet.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/LocationText.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/PrimaryButton.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/SpeechBubble.kt
  app/src/main/res/drawable/ic_all_current_location.xml
  app/src/main/res/drawable/ic_home_current_location.xml
  app/src/main/res/values/strings.xml
Labels: feat

#89 [#65] : 경로 상세 화면 업데이트
  app/build.gradle.kts
  app/proguard-rules.pro
  app/release/baselineProfiles/0/app-release.dm
  app/release/baselineProfiles/1/app-release.dm
  app/release/output-metadata.json
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/base/ApiResponse.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/locations/ResponseAddressDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/locations/ResponseLocationsDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/transits/ResponseBusArrivalsDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/transits/ResponseBusPositionsDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/transits/ResponseCourseSearchDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/user/ResponseAuthDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/user/ResponseCheckDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/user/ResponseReissueDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/user/ResponseUserInfoDto.kt
  app/src/main/java/com/depromeet/team6/data/mapper/todomain/ResponseCourseSearchDtoMapper.kt
  app/src/main/java/com/depromeet/team6/domain/model/course/CourseInfo.kt
  app/src/main/java/com/depromeet/team6/domain/model/course/LegInfo.kt
  app/src/main/java/com/depromeet/team6/presentation/model/itinerary/FocusedMarkerParameter.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/BusCourseScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/common/AtchaCommonBottomSheet.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/CourseSearchScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/CourseSearchViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/CourseInfoSimple.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/LastTransportInfoItem.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/LastTransportInfoList.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/TransportTabMenu.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/TransportTabRow.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/navigation/CourseSearchNavigation.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/AfterRegisterMap.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/ItineraryContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/ItineraryScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/ItineraryViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/LegInfoDummyProvider.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/component/ItineraryDetail.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/component/ItineraryInfoDetail.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/component/ItineraryInfoDetailLegs.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/component/ItineraryMap.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/component/ItinerarySummary.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/component/SummaryBarChart.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/navigation/ItineraryNavigation.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/navigation/MainNavHost.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/navigation/MainNavigator.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/SearchLocationContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/SearchLocationScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/component/SearchLocationMapView.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/component/SearchLocationTextField.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/navigation/SearchLocationNavigation.kt
  app/src/main/java/com/depromeet/team6/presentation/util/Dimens.kt
  app/src/main/res/drawable/ic_arrow_down_big.xml
  app/src/main/res/drawable/ic_arrow_right_big.xml
  app/src/main/res/values/strings.xml
Labels: feat

#100 [#94] 말풍선 색상 원복 및 홈 높이 조정
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/CourseDetailButton.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/DeleteAlarmDialog.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/MapView.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/SpeechBubble.kt
  app/src/main/res/drawable/ic_home_current_location.xml
Labels: fix

#102 [#101]최근 검색 내역 삭제 서버 변경 반영
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/LocationsRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/LocationsService.kt
  app/src/main/java/com/depromeet/team6/data/repositoryimpl/LocationsRepositoryImpl.kt
  app/src/main/java/com/depromeet/team6/domain/repository/LocationsRepository.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/DeleteSearchHistoryUseCase.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/SpeechBubble.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/component/SearchLocationTextField.kt
Labels: feat

#106 [#94] 네비게이션 바 검정색 색상 전체 적용
  app/build.gradle.kts
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/MainActivity.kt
  gradle/libs.versions.toml
Labels: feat

#108 [#107] 말풍선 말꼬리 수정
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/SpeechBubble.kt
Labels: feat, refactor

#109 [#72]: 버스 운행정보 UI 구현
  .kotlin/sessions/kotlin-compiler-15018342916107271600.salive
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/TransitsRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/transits/ResponseBusPositionsDto.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/TransitsService.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/util/Constraints.kt
  app/src/main/java/com/depromeet/team6/data/mapper/todomain/ResponseBusOperationInfoDtoMapper.kt
  app/src/main/java/com/depromeet/team6/data/repositoryimpl/TransitsRepositoryImpl.kt
  app/src/main/java/com/depromeet/team6/domain/model/BusOperationInfo.kt
  app/src/main/java/com/depromeet/team6/domain/repository/TransitsRepository.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetBusOperationInfoUseCase.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/BusCourseContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/BusCourseScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/BusCourseViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/component/BusOperationInfo.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/common/view/AtChaLoadingView.kt
  app/src/main/java/com/depromeet/team6/presentation/util/Constraints.kt
  app/src/main/res/drawable/ic_all_arrow_left_right_12.xml
  app/src/main/res/raw/atcha_loading.json
Labels: feat

#123 [#122] 홈 유저 데이터 트래킹
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/CurrentLocationSheet.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/LocationText.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/MapView.kt
  app/src/main/java/com/depromeet/team6/presentation/util/Constraints.kt
Labels: feat

#129 [#128] Fcm Token 비어있는 버그 수정
  app/src/main/java/com/depromeet/team6/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/OnboardingViewModel.kt
Labels: bug, fix
