Repository depromeet/16th-team6-Android, pull requests merged in 2025-07, with the labels that each got.

#153 [#137] 오후 10시 앱 사용 유도 알림 구현
  A
  Get
  KtLint
  Run
  Task
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/depromeet/team6/Team6App.kt
  app/src/main/java/com/depromeet/team6/data/datalocal/manager/BaseForegroundServiceManager.kt
  app/src/main/java/com/depromeet/team6/data/datalocal/service/LocationCheckReceiver.kt
  app/src/main/java/com/depromeet/team6/data/datalocal/service/LockService.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/alarm/NotificationReceiver.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/alarm/NotificationScheduler.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/alarm/NotificationTimeConstants.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeScreen.kt
  app/src/main/res/values/strings.xml
Labels: feat

#162 [#160] 담당 API (유저, 버스 관련) 서버 에러 핸들링 구현
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/AuthRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/LocationsRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/TransitsRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/base/ApiResponse.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/AuthService.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/LocationsService.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/TransitsService.kt
  app/src/main/java/com/depromeet/team6/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/com/depromeet/team6/domain/ErrorConstraints.kt
  app/src/main/java/com/depromeet/team6/domain/repository/AuthRepository.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/DeleteWithDrawUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetBusArrivalUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetBusOperationInfoUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetBusPositionsUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetBusStartedUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetCheckUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetCourseSearchResultsUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetLocationsUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetLoginUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/PostLogoutUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/PostSignUpUseCase.kt
  app/src/main/java/com/depromeet/team6/presentation/model/exception/ErrorControlFailureException.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/BusCourseViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/ItineraryViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/mypage/MypageViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/SearchLocationViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/util/ErrorToastMessage.kt
  app/src/main/java/com/depromeet/team6/presentation/util/base/BaseViewModel.kt
Labels: feat

#169 [#167] 로그인, 온보딩, 홈 진입 플로우 QA사항 적용
  app/src/main/java/com/depromeet/team6/data/dataremote/service/TransitsService.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/common/view/AtChaThreeDotsLoadingView.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/HomeGreetBottomSheet.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/login/LoginContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/login/LoginScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/navigation/MainNavHost.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/navigation/MainNavigator.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/component/OnboardingMapView.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/component/OnboardingSearchPopup.kt
  app/src/main/java/com/depromeet/team6/presentation/util/modifier/ModifierExt.kt
  app/src/main/res/drawable/ic_home_greet_bottom_sheet.xml
  app/src/main/res/values/strings.xml
Labels: fix

#159 [#155] 알림, 회원 정보 API 에러 핸들링 구현
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/AlarmRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/AuthRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/AlarmService.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/AuthService.kt
  app/src/main/java/com/depromeet/team6/data/repositoryimpl/AlarmRepositoryImpl.kt
  app/src/main/java/com/depromeet/team6/domain/ErrorConstraints.kt
  app/src/main/java/com/depromeet/team6/domain/repository/AlarmRepository.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/DeleteAlarmUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetUserInfoUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/ModifyUserInfoUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/PostAlarmUseCase.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/CourseSearchViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/ItineraryScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/ItineraryViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/navigation/ItineraryNavigation.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/navigation/MainNavHost.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/mypage/MypageScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/mypage/MypageViewModel.kt
Labels: feat

#175 [#172] 알림 등록 후 홈화면 로직 변경 & 버그 수정
  app/src/main/java/com/depromeet/team6/data/datalocal/datasource/HomeInfoLocalDataSource.kt
  app/src/main/java/com/depromeet/team6/data/repositoryimpl/HomeRepositoryImpl.kt
  app/src/main/java/com/depromeet/team6/domain/repository/HomeRepository.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/CourseSearchScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/CourseSearchViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/AfterRegisterMap.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/mypage/MypageViewModel.kt
Labels: fix, refactor

#173 [#168] 경로검색 화면 렌더링 최적화 및 데이터 버그 수정
  .DS_Store
  app/.DS_Store
  app/build.gradle.kts
  app/debug/.DS_Store
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/TransitsRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/request/transits/RequestBusArrivalDTO.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/TransitsService.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/util/Constraints.kt
  app/src/main/java/com/depromeet/team6/data/mapper/todomain/ResponseCourseSearchDtoMapper.kt
  app/src/main/java/com/depromeet/team6/data/repositoryimpl/TransitsRepositoryImpl.kt
  app/src/main/java/com/depromeet/team6/domain/model/course/LegInfo.kt
  app/src/main/java/com/depromeet/team6/domain/repository/TransitsRepository.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetBusArrivalUseCase.kt
  app/src/main/java/com/depromeet/team6/presentation/model/bus/BusArrivalParameter.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/BusCourseContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/BusCourseScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/BusCourseViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/navigation/BusCourseNavigation.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/CourseSearchScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/CourseSearchViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/navigation/CourseSearchNavigation.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/LastTimer.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/ItineraryViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/component/ItineraryDetail.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/component/ItineraryInfoDetailLegs.kt
  app/src/main/res/values/strings.xml
Labels: feat

#182 [#181] 메인 화면 모달 및 지도 위치 수정
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/MapView.kt
Labels: fix

#178 [#174] 권한 팝업 로직 수정
  app/src/main/java/com/depromeet/team6/data/datalocal/datasource/UserInfoLocalDataSource.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/common/dialog/GlobalDialogHnadler.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/common/dialog/SystemSettingsDialog.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/CharacterSpeechBubble.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/MainViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/mypage/MypageContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/mypage/MypageScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/mypage/MypageViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/OnboardingContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/OnboardingScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/component/OnboardingPermissionDeniedBottomSheet.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/component/OnboardingSearchPopup.kt
  app/src/main/java/com/depromeet/team6/presentation/util/context/ContextExt.kt
  app/src/main/java/com/depromeet/team6/presentation/util/dialog/DialogController.kt
  app/src/main/java/com/depromeet/team6/presentation/util/permission/PermissionUtil.kt
  app/src/main/res/drawable/ic_all_atcha_character.xml
  app/src/main/res/values/strings.xml
Labels: fix

#186 [#177] 알람기능 클라이언트 제어 방식으로 리팩토링
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/depromeet/team6/Team6App.kt
  app/src/main/java/com/depromeet/team6/data/background/AlarmReceiver.kt
  app/src/main/java/com/depromeet/team6/data/background/AlarmScheduler.kt
  app/src/main/java/com/depromeet/team6/data/background/BaseForegroundServiceManager.kt
  app/src/main/java/com/depromeet/team6/data/background/FcmService.kt
  app/src/main/java/com/depromeet/team6/data/background/LocationCheckReceiver.kt
  app/src/main/java/com/depromeet/team6/data/background/LockReceiver.kt
  app/src/main/java/com/depromeet/team6/data/background/LockService.kt
  app/src/main/java/com/depromeet/team6/data/background/NotificationHelper.kt
  app/src/main/java/com/depromeet/team6/data/datalocal/datasource/AlarmFiredLocalDataSource.kt
  app/src/main/java/com/depromeet/team6/data/datalocal/datasource/HomeInfoLocalDataSource.kt
  app/src/main/java/com/depromeet/team6/data/datalocal/manager/Extension.kt
  app/src/main/java/com/depromeet/team6/data/datalocal/service/LocationCheckReceiver.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/AlarmRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/LocationsRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/alarm/ResponseAlarmRefreshDTO.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/AlarmService.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/HomeService.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/LocationsService.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/TimeLeftService.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/TransitsService.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/util/Constraints.kt
  app/src/main/java/com/depromeet/team6/data/repositoryimpl/AlarmRepositoryImpl.kt
  app/src/main/java/com/depromeet/team6/data/repositoryimpl/HomeRepositoryImpl.kt
  app/src/main/java/com/depromeet/team6/domain/ErrorConstraints.kt
  app/src/main/java/com/depromeet/team6/domain/repository/AlarmRepository.kt
  app/src/main/java/com/depromeet/team6/domain/repository/HomeRepository.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/InitAlarmUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/RefreshAlarmTimerUseCase.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/BusCourseScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/CourseSearchScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/CourseSearchViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/LastTransportInfoItem.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/component/LastTransportInfoList.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/AfterRegisterSheet.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/ItineraryScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/itinerary/ItineraryViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/lock/LockActivity.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/MainViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/util/Constraints.kt
Labels: feat

#198 [#197] 홈 화면 버튼 위치 수정
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/MapView.kt
Labels: fix

#194 [#193] : 사용자 위치 정류장 판단로직 수정
  app/src/main/java/com/depromeet/team6/presentation/ui/bus/BusCourseScreen.kt
Labels: fix
