Repository depromeet/16th-team6-Android, pull requests merged in 2025-06, with the labels that each got.

#130 [#127] 홈 로딩 애니메이션 적용
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/SearchLocationScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/component/SearchLocationTextField.kt
Labels: feat

#116 [#112] 알림 등록 후 홈 화면 추가 구현
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/AfterRegisterMap.kt
Labels: feat

#152 feat/#149 : 피드백 배너 구현
  app/src/main/java/com/depromeet/team6/presentation/ui/mypage/MypageChangeHomeScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/mypage/MypageContract.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/mypage/MypageScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/mypage/MypageViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/util/Constraints.kt
  app/src/main/res/drawable/ic_mypage_banner.xml
Labels: feat

#146 [#145] 유저정보 조회 APII providerId Type 수정
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/user/ResponseUserInfoDto.kt
  app/src/main/java/com/depromeet/team6/domain/model/UserInfo.kt
Labels: refactor

#148 [#147] 서버 에러 핸들링 파이프라인 구축
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/HomeRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/LocationsRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/TaxiCostRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/datasource/TransitsRemoteDataSource.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/interceptor/AuthInterceptor.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/request/exeption/RequestException.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/base/ApiErrorResponse.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/base/ApiException.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/model/response/base/ApiResponse.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/HomeService.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/LocationsService.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/TaxiCostService.kt
  app/src/main/java/com/depromeet/team6/data/dataremote/service/TransitsService.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetAddressFromCoordinatesUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetBusStartedUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/GetCourseSearchResultsUseCase.kt
  app/src/main/java/com/depromeet/team6/domain/usecase/base/ApiRequestUseCase.kt
  app/src/main/java/com/depromeet/team6/presentation/model/exception/ErrorControlFailureException.kt
  app/src/main/java/com/depromeet/team6/presentation/model/route/Route.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/CourseSearchScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/CourseSearchViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/coursesearch/navigation/CourseSearchNavigation.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeScreen.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/MapView.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/main/navigation/MainNavHost.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/mypage/MypageViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/ui/searchlocation/SearchLocationViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/util/ErrorToastMessage.kt
  app/src/main/java/com/depromeet/team6/presentation/util/base/ApiErrorSideEffect.kt
  app/src/main/java/com/depromeet/team6/presentation/util/base/BaseViewModel.kt
  app/src/main/java/com/depromeet/team6/presentation/util/context/ContextExt.kt
Labels: feat

#157 [#156] 목적지 도착 토스트 메시지 뜨는 시점 해결
  app/src/main/java/com/depromeet/team6/presentation/ui/home/component/AfterRegisterMap.kt
Labels: bug, fix
